テストコード修正
UMA-no9/rspec_app_exam pull request #2
Opened 2021-03-11 15:01 UTC by UMA-no9

概要
- FIXME/TODOの指示に従ってspec/system/taskのコードを修正

変更点
- クラス名[FactoryBot]の省略
- ローカル変数で定義されている部分をletでの定義に置換
- factories/tasksにprojectとのアソシエーション、ならびに完了済みtaskのtraitを追加
- factoryの変更にともなうコードの修正
- テストが失敗する部分の修正
- その他、細かな修正

2021-03-12 03:33 UTC, yuji91 requested changes
気になった点をコメントしました！

またこのページのコード差分がレビュアーに取って読み取りづらくなっているので、本当の現場だったら作り直した方が良いという点は意識しておいてくださいm(_ _)m

2021-03-12 03:33 UTC, yuji91 commented on spec/system/task_spec.rb
> -  let(:project) { create(:project) }
`project`単体でテストデータを作成したい場合もあると思うので、この行は独立して残しておいた方が良いかと思います！

2021-03-12 03:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(task.deadline.strftime('%-m/%d %-H:%M'))
`strftime('%-m/%d %-H:%M')`を編集した形では、View側のメソッドの仕様が変わるとテストが失敗してしまいます。NG例のPullRequestも参考にしてください。

2021-03-14 05:34 UTC, UMA-no9 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(task.deadline.strftime('%-m/%d %-H:%M'))
7643c0e 修正しました。

2021-03-14 05:36 UTC, UMA-no9 commented on spec/system/task_spec.rb
> -  let(:project) { create(:project) }
bb7236e b3d4246 修正しました。

2021-03-14 05:39 UTC, UMA-no9 commented
メッセージ内容と関係のない修正が混在しているコミットがありましたので、以降はコミットを細かく分けるようにいたします。

2021-03-15 02:19 UTC, yuji91 approved these changes

2021-03-15 02:56 UTC, merged